default: prog

prog: main.o
	g++ main.o -o prog -L C:\Users\ManiacalDrWatts\Desktop\OpenGL\lib
main.o: main.cpp
	g++ main.cpp -c -I C:\Users\ManiacalDrWatts\Desktop\OpenGL\include


clean:
	rm -rf *.o prog.exe a.exe out.ppm